import {
  PropertyGroup,
  PropertyGroupType,
  PropertyGroupStatus,
  LegalForm,
  PropertyGroupContact,
  ContactRole,
  PersonType,
  PreferredContactMethod,
  PropertyGroupStats,
} from "../types/property-group.types";

// Mock Contacts
export const mockContacts: PropertyGroupContact[] = [
  {
    id: "contact-1",
    propertyGroupId: "1",
    role: ContactRole.GeneralManager,
    personType: PersonType.Individual,
    firstName: "Jean",
    lastName: "Dupont",
    position: "Directeur Général",
    department: "Direction",
    email: "jean.dupont@groupe-paris.fr",
    phone: "+33 1 23 45 67 89",
    mobile: "+33 6 12 34 56 78",
    isPrimary: true,
    receivesInvoices: true,
    receivesReports: true,
    receivesAlerts: true,
    preferredContactMethod: PreferredContactMethod.Email,
    notes: "Contact principal pour toutes les décisions stratégiques",
    created: "2024-01-15T10:00:00Z",
    lastModified: "2024-01-15T10:00:00Z",
  },
  {
    id: "contact-2",
    propertyGroupId: "1",
    role: ContactRole.AccountingManager,
    personType: PersonType.Individual,
    firstName: "Sophie",
    lastName: "Bernard",
    position: "Responsable Comptabilité",
    department: "Comptabilité",
    email: "sophie.bernard@groupe-paris.fr",
    phone: "+33 1 23 45 67 90",
    mobile: "+33 6 23 45 67 89",
    isPrimary: false,
    receivesInvoices: true,
    receivesReports: false,
    receivesAlerts: false,
    preferredContactMethod: PreferredContactMethod.Email,
    notes: "Contacter uniquement pour les questions de facturation",
    created: "2024-01-15T10:00:00Z",
    lastModified: "2024-01-15T10:00:00Z",
  },
  {
    id: "contact-3",
    propertyGroupId: "1",
    role: ContactRole.TechnicalManager,
    personType: PersonType.Individual,
    firstName: "Pierre",
    lastName: "Moreau",
    position: "Responsable Technique",
    department: "Technique",
    email: "pierre.moreau@groupe-paris.fr",
    phone: "+33 1 23 45 67 91",
    mobile: "+33 6 34 56 78 90",
    isPrimary: false,
    receivesInvoices: false,
    receivesReports: true,
    receivesAlerts: true,
    preferredContactMethod: PreferredContactMethod.Phone,
    notes: "Disponible 24/7 pour les urgences techniques",
    created: "2024-01-15T10:00:00Z",
    lastModified: "2024-01-15T10:00:00Z",
  },
  {
    id: "contact-4",
    propertyGroupId: "2",
    role: ContactRole.GeneralManager,
    personType: PersonType.Individual,
    firstName: "Marie",
    lastName: "Martin",
    position: "Directrice",
    department: "Direction",
    email: "marie.martin@syndic-lyon.fr",
    phone: "+33 4 12 34 56 78",
    mobile: "+33 6 45 67 89 01",
    isPrimary: true,
    receivesInvoices: true,
    receivesReports: true,
    receivesAlerts: true,
    preferredContactMethod: PreferredContactMethod.Email,
    created: "2024-02-10T14:30:00Z",
    lastModified: "2024-02-10T14:30:00Z",
  },
  {
    id: "contact-5",
    propertyGroupId: "2",
    role: ContactRole.CustomerServiceManager,
    personType: PersonType.Individual,
    firstName: "Luc",
    lastName: "Dubois",
    position: "Responsable Service Client",
    department: "Service Client",
    email: "luc.dubois@syndic-lyon.fr",
    phone: "+33 4 12 34 56 79",
    mobile: "+33 6 56 78 90 12",
    isPrimary: false,
    receivesInvoices: false,
    receivesReports: true,
    receivesAlerts: true,
    preferredContactMethod: PreferredContactMethod.SMS,
    notes: "Premier point de contact pour les réclamations",
    created: "2024-02-10T14:30:00Z",
    lastModified: "2024-02-10T14:30:00Z",
  },
  {
    id: "contact-6",
    propertyGroupId: "3",
    role: ContactRole.GeneralManager,
    personType: PersonType.Individual,
    firstName: "Claire",
    lastName: "Rousseau",
    position: "PDG",
    department: "Direction",
    email: "claire.rousseau@investcorp.fr",
    phone: "+33 1 45 67 89 01",
    mobile: "+33 6 67 89 01 23",
    isPrimary: true,
    receivesInvoices: true,
    receivesReports: true,
    receivesAlerts: true,
    preferredContactMethod: PreferredContactMethod.Email,
    created: "2024-03-05T09:00:00Z",
    lastModified: "2024-03-05T09:00:00Z",
  },
];

// Mock Property Groups
export const mockPropertyGroups: PropertyGroup[] = [
  {
    id: "1",
    reference: "GRP-001",
    name: "Groupe Immobilier Paris",
    description: "Principal groupe immobilier parisien spécialisé dans la gestion de copropriétés haut de gamme",
    type: PropertyGroupType.PropertyManagementCompany,
    status: PropertyGroupStatus.Active,
    legalName: "SAS Groupe Immobilier Paris",
    siren: "123456789",
    companyRegistrationNumber: "RCS Paris 123 456 789",
    vatNumber: "FR12345678901",
    legalForm: LegalForm.SAS,
    headquartersAddress: {
      firstAddressLine: "Tour Montparnasse",
      secondAddressLine: "Bureau 45",
      street: "123 Avenue des Champs-Élysées",
      city: "Paris",
      postalCode: "75008",
      country: "France",
    },
    mainContactName: "Jean Dupont",
    mainContactPosition: "Directeur Général",
    mainContactEmail: "jean.dupont@groupe-paris.fr",
    mainContactPhone: "+33 1 23 45 67 89",
    mainContactMobile: "+33 6 12 34 56 78",
    accountingContactName: "Sophie Bernard",
    accountingContactEmail: "comptabilite@groupe-paris.fr",
    accountingContactPhone: "+33 1 23 45 67 90",
    consolidatedBilling: true,
    paymentTermsDays: 30,
    volumeDiscountPercent: 5,
    preferredPaymentMethod: "Virement bancaire",
    groupPricingCoefficients: {
      laborCoefficient: 1.30,
      materialCoefficient: 1.25,
      equipmentCoefficient: 1.20,
      subcontractorCoefficient: 1.15,
      volumeDiscountPercent: 5,
      minimumAnnualRevenue: 100000,
      emergencyCalloutFee: 150,
      monthlyMaintenanceFee: 500,
    },
    totalCustomers: 45,
    totalSites: 120,
    totalUnits: 850,
    totalAnnualRevenue: 2500000,
    lastStatisticsUpdateDate: "2024-11-01T10:00:00Z",
    frameworkContractStartDate: "2024-01-01",
    frameworkContractEndDate: "2025-12-31",
    frameworkContractReference: "CONT-2024-001",
    autoRenewalFrameworkContract: false,
    internalNotes: "Excellent client, toujours à jour dans ses paiements. Prévoir une révision des tarifs en fin d'année.",
    commercialNotes: "Opportunité d'extension du contrat pour 3 nouveaux sites en 2025.",
    contacts: mockContacts.filter(c => c.propertyGroupId === "1"),
    created: "2024-01-15T10:00:00Z",
    createdBy: "admin@gmao.fr",
    lastModified: "2024-11-05T15:30:00Z",
    lastModifiedBy: "jean.dupont@gmao.fr",
  },
  {
    id: "2",
    reference: "GRP-002",
    name: "Syndic Lyon Centre",
    description: "Syndic spécialisé dans le centre historique de Lyon avec expertise en immeubles classés",
    type: PropertyGroupType.SyndicGroup,
    status: PropertyGroupStatus.Active,
    legalName: "SARL Syndic Lyon Centre",
    siren: "987654321",
    companyRegistrationNumber: "RCS Lyon 987 654 321",
    vatNumber: "FR98765432109",
    legalForm: LegalForm.SARL,
    headquartersAddress: {
      street: "45 Rue de la République",
      city: "Lyon",
      postalCode: "69002",
      country: "France",
    },
    mainContactName: "Marie Martin",
    mainContactPosition: "Directrice",
    mainContactEmail: "marie.martin@syndic-lyon.fr",
    mainContactPhone: "+33 4 12 34 56 78",
    mainContactMobile: "+33 6 45 67 89 01",
    accountingContactName: "Luc Dubois",
    accountingContactEmail: "compta@syndic-lyon.fr",
    accountingContactPhone: "+33 4 12 34 56 79",
    consolidatedBilling: false,
    paymentTermsDays: 45,
    volumeDiscountPercent: 3,
    preferredPaymentMethod: "Chèque",
    groupPricingCoefficients: {
      laborCoefficient: 1.35,
      materialCoefficient: 1.28,
      equipmentCoefficient: 1.22,
      subcontractorCoefficient: 1.18,
      volumeDiscountPercent: 3,
      minimumAnnualRevenue: 50000,
      emergencyCalloutFee: 180,
      monthlyMaintenanceFee: 450,
    },
    totalCustomers: 28,
    totalSites: 65,
    totalUnits: 420,
    totalAnnualRevenue: 1200000,
    lastStatisticsUpdateDate: "2024-10-25T14:00:00Z",
    frameworkContractStartDate: "2023-06-01",
    frameworkContractEndDate: "2026-05-31",
    frameworkContractReference: "CONT-2023-045",
    autoRenewalFrameworkContract: true,
    internalNotes: "Client fidèle depuis 5 ans. Attention aux délais de paiement parfois longs.",
    commercialNotes: "Intéressé par nos services de maintenance préventive pour 2025.",
    contacts: mockContacts.filter(c => c.propertyGroupId === "2"),
    created: "2024-02-10T14:30:00Z",
    createdBy: "admin@gmao.fr",
    lastModified: "2024-10-28T11:20:00Z",
    lastModifiedBy: "marie.martin@gmao.fr",
  },
  {
    id: "3",
    reference: "GRP-003",
    name: "Invest Corp Méditerranée",
    description: "Investisseur immobilier spécialisé dans les résidences de tourisme sur la Côte d'Azur",
    type: PropertyGroupType.RealEstateInvestor,
    status: PropertyGroupStatus.Active,
    legalName: "SA Invest Corp Méditerranée",
    siren: "456789123",
    companyRegistrationNumber: "RCS Nice 456 789 123",
    vatNumber: "FR45678912301",
    legalForm: LegalForm.SA,
    headquartersAddress: {
      firstAddressLine: "Immeuble Le Grand Bleu",
      street: "78 Promenade des Anglais",
      city: "Nice",
      postalCode: "06000",
      country: "France",
    },
    mainContactName: "Claire Rousseau",
    mainContactPosition: "PDG",
    mainContactEmail: "claire.rousseau@investcorp.fr",
    mainContactPhone: "+33 1 45 67 89 01",
    mainContactMobile: "+33 6 67 89 01 23",
    accountingContactName: "Thomas Petit",
    accountingContactEmail: "finances@investcorp.fr",
    accountingContactPhone: "+33 1 45 67 89 02",
    consolidatedBilling: true,
    paymentTermsDays: 60,
    volumeDiscountPercent: 8,
    preferredPaymentMethod: "Virement SEPA",
    groupPricingCoefficients: {
      laborCoefficient: 1.25,
      materialCoefficient: 1.22,
      equipmentCoefficient: 1.18,
      subcontractorCoefficient: 1.12,
      volumeDiscountPercent: 8,
      minimumAnnualRevenue: 200000,
      emergencyCalloutFee: 200,
      monthlyMaintenanceFee: 800,
    },
    totalCustomers: 12,
    totalSites: 35,
    totalUnits: 680,
    totalAnnualRevenue: 3800000,
    lastStatisticsUpdateDate: "2024-11-08T09:00:00Z",
    frameworkContractStartDate: "2024-03-01",
    frameworkContractEndDate: "2027-02-28",
    frameworkContractReference: "CONT-2024-089",
    autoRenewalFrameworkContract: true,
    internalNotes: "Client premium, très exigeant sur la qualité. Budget important.",
    commercialNotes: "En discussion pour 5 nouveaux sites prévus pour 2025-2026.",
    contacts: mockContacts.filter(c => c.propertyGroupId === "3"),
    created: "2024-03-05T09:00:00Z",
    createdBy: "admin@gmao.fr",
    lastModified: "2024-11-08T09:30:00Z",
    lastModifiedBy: "claire.rousseau@gmao.fr",
  },
  {
    id: "4",
    reference: "GRP-004",
    name: "Habitat Social Bretagne",
    description: "Bailleur social régional gérant un parc de logements sociaux",
    type: PropertyGroupType.PublicHousing,
    status: PropertyGroupStatus.Active,
    legalName: "OPH Habitat Social Bretagne",
    siren: "789456123",
    companyRegistrationNumber: "SIREN 789 456 123",
    vatNumber: "FR78945612301",
    legalForm: LegalForm.PublicEntity,
    headquartersAddress: {
      street: "15 Boulevard de la Liberté",
      city: "Rennes",
      postalCode: "35000",
      country: "France",
    },
    mainContactName: "François Legrand",
    mainContactPosition: "Directeur Général",
    mainContactEmail: "francois.legrand@habitat-bretagne.fr",
    mainContactPhone: "+33 2 99 12 34 56",
    mainContactMobile: "+33 6 78 90 12 34",
    accountingContactName: "Isabelle Leroy",
    accountingContactEmail: "compta@habitat-bretagne.fr",
    accountingContactPhone: "+33 2 99 12 34 57",
    consolidatedBilling: true,
    paymentTermsDays: 30,
    volumeDiscountPercent: 10,
    preferredPaymentMethod: "Virement bancaire",
    groupPricingCoefficients: {
      laborCoefficient: 1.20,
      materialCoefficient: 1.18,
      equipmentCoefficient: 1.15,
      subcontractorCoefficient: 1.10,
      volumeDiscountPercent: 10,
      minimumAnnualRevenue: 150000,
      emergencyCalloutFee: 120,
      monthlyMaintenanceFee: 600,
    },
    totalCustomers: 1,
    totalSites: 85,
    totalUnits: 1250,
    totalAnnualRevenue: 1800000,
    lastStatisticsUpdateDate: "2024-11-01T08:00:00Z",
    frameworkContractStartDate: "2023-01-01",
    frameworkContractEndDate: "2026-12-31",
    frameworkContractReference: "MARCHE-2023-001",
    autoRenewalFrameworkContract: false,
    internalNotes: "Marché public avec procédures strictes. Respecter les délais de facturation.",
    commercialNotes: "Renouvellement du marché prévu en 2026.",
    contacts: [],
    created: "2023-12-01T10:00:00Z",
    createdBy: "admin@gmao.fr",
    lastModified: "2024-11-01T10:00:00Z",
    lastModifiedBy: "admin@gmao.fr",
  },
  {
    id: "5",
    reference: "GRP-005",
    name: "Tech Corporate Solutions",
    description: "Entreprise de technologie gérant son propre parc immobilier de bureaux",
    type: PropertyGroupType.Corporate,
    status: PropertyGroupStatus.Active,
    legalName: "SAS Tech Corporate Solutions",
    siren: "321654987",
    companyRegistrationNumber: "RCS Paris 321 654 987",
    vatNumber: "FR32165498701",
    legalForm: LegalForm.SAS,
    headquartersAddress: {
      firstAddressLine: "Campus Tech Valley",
      secondAddressLine: "Bâtiment A",
      street: "99 Avenue de la Grande Armée",
      city: "Paris",
      postalCode: "75016",
      country: "France",
    },
    mainContactName: "Alexandre Blanc",
    mainContactPosition: "Directeur des Services Généraux",
    mainContactEmail: "alexandre.blanc@techcorp.fr",
    mainContactPhone: "+33 1 56 78 90 12",
    mainContactMobile: "+33 6 89 01 23 45",
    accountingContactName: "Julie Mercier",
    accountingContactEmail: "julie.mercier@techcorp.fr",
    accountingContactPhone: "+33 1 56 78 90 13",
    consolidatedBilling: true,
    paymentTermsDays: 45,
    volumeDiscountPercent: 7,
    preferredPaymentMethod: "Virement bancaire",
    groupPricingCoefficients: {
      laborCoefficient: 1.28,
      materialCoefficient: 1.24,
      equipmentCoefficient: 1.19,
      subcontractorCoefficient: 1.14,
      volumeDiscountPercent: 7,
      minimumAnnualRevenue: 180000,
      emergencyCalloutFee: 175,
      monthlyMaintenanceFee: 700,
    },
    totalCustomers: 1,
    totalSites: 8,
    totalUnits: 450,
    totalAnnualRevenue: 2200000,
    lastStatisticsUpdateDate: "2024-11-07T16:00:00Z",
    frameworkContractStartDate: "2024-06-01",
    frameworkContractEndDate: "2025-05-31",
    frameworkContractReference: "CONT-2024-156",
    autoRenewalFrameworkContract: true,
    internalNotes: "Client exigeant mais professionnel. Besoins spécifiques pour data centers.",
    commercialNotes: "Expansion prévue avec 2 nouveaux sites en 2025.",
    contacts: [],
    created: "2024-05-15T14:00:00Z",
    createdBy: "admin@gmao.fr",
    lastModified: "2024-11-07T16:30:00Z",
    lastModifiedBy: "alexandre.blanc@gmao.fr",
  },
  {
    id: "6",
    reference: "GRP-006",
    name: "Family Office Dupuis",
    description: "Family office gérant un patrimoine immobilier diversifié",
    type: PropertyGroupType.FamilyOffice,
    status: PropertyGroupStatus.Prospect,
    legalName: "SCI Family Office Dupuis",
    siren: "147258369",
    companyRegistrationNumber: "RCS Bordeaux 147 258 369",
    vatNumber: "FR14725836901",
    legalForm: LegalForm.SCI,
    headquartersAddress: {
      street: "34 Cours de l'Intendance",
      city: "Bordeaux",
      postalCode: "33000",
      country: "France",
    },
    mainContactName: "Philippe Dupuis",
    mainContactPosition: "Gérant",
    mainContactEmail: "philippe.dupuis@fo-dupuis.fr",
    mainContactPhone: "+33 5 56 12 34 56",
    mainContactMobile: "+33 6 90 12 34 56",
    consolidatedBilling: false,
    paymentTermsDays: 30,
    totalCustomers: 0,
    totalSites: 0,
    totalUnits: 0,
    totalAnnualRevenue: 0,
    autoRenewalFrameworkContract: false,
    commercialNotes: "Prospect intéressant avec un patrimoine estimé de 15M€. En phase de négociation.",
    contacts: [],
    created: "2024-10-20T11:00:00Z",
    createdBy: "commercial@gmao.fr",
    lastModified: "2024-11-08T09:00:00Z",
    lastModifiedBy: "commercial@gmao.fr",
  },
  {
    id: "7",
    reference: "GRP-007",
    name: "Résidences Senior Provence",
    description: "Exploitant de résidences services seniors",
    type: PropertyGroupType.PropertyManagementCompany,
    status: PropertyGroupStatus.Active,
    legalName: "SAS Résidences Senior Provence",
    siren: "258369147",
    companyRegistrationNumber: "RCS Marseille 258 369 147",
    vatNumber: "FR25836914701",
    legalForm: LegalForm.SAS,
    headquartersAddress: {
      street: "88 La Canebière",
      city: "Marseille",
      postalCode: "13001",
      country: "France",
    },
    mainContactName: "Catherine Blanc",
    mainContactPosition: "Directrice Générale",
    mainContactEmail: "catherine.blanc@senior-provence.fr",
    mainContactPhone: "+33 4 91 12 34 56",
    mainContactMobile: "+33 6 01 23 45 67",
    accountingContactName: "Marc Vincent",
    accountingContactEmail: "comptabilite@senior-provence.fr",
    accountingContactPhone: "+33 4 91 12 34 57",
    consolidatedBilling: true,
    paymentTermsDays: 30,
    volumeDiscountPercent: 6,
    preferredPaymentMethod: "Prélèvement automatique",
    groupPricingCoefficients: {
      laborCoefficient: 1.32,
      materialCoefficient: 1.26,
      equipmentCoefficient: 1.21,
      subcontractorCoefficient: 1.16,
      volumeDiscountPercent: 6,
      minimumAnnualRevenue: 120000,
      emergencyCalloutFee: 160,
      monthlyMaintenanceFee: 550,
    },
    totalCustomers: 6,
    totalSites: 18,
    totalUnits: 380,
    totalAnnualRevenue: 1650000,
    lastStatisticsUpdateDate: "2024-10-30T10:00:00Z",
    frameworkContractStartDate: "2024-04-01",
    frameworkContractEndDate: "2027-03-31",
    frameworkContractReference: "CONT-2024-112",
    autoRenewalFrameworkContract: true,
    internalNotes: "Secteur spécifique avec normes strictes. Personnel formé aux ERP type J.",
    commercialNotes: "Ouverture de 2 nouvelles résidences prévue en 2025.",
    contacts: [],
    created: "2024-03-20T13:00:00Z",
    createdBy: "admin@gmao.fr",
    lastModified: "2024-10-30T11:00:00Z",
    lastModifiedBy: "catherine.blanc@gmao.fr",
  },
  {
    id: "8",
    reference: "GRP-008",
    name: "Hôtels Prestige International",
    description: "Chaîne hôtelière de standing",
    type: PropertyGroupType.Corporate,
    status: PropertyGroupStatus.Suspended,
    legalName: "SA Hôtels Prestige International",
    siren: "369147258",
    companyRegistrationNumber: "RCS Paris 369 147 258",
    vatNumber: "FR36914725801",
    legalForm: LegalForm.SA,
    headquartersAddress: {
      street: "56 Rue du Faubourg Saint-Honoré",
      city: "Paris",
      postalCode: "75008",
      country: "France",
    },
    mainContactName: "Laurent Mercier",
    mainContactPosition: "Directeur Technique",
    mainContactEmail: "laurent.mercier@hotels-prestige.fr",
    mainContactPhone: "+33 1 67 89 01 23",
    consolidatedBilling: true,
    paymentTermsDays: 60,
    volumeDiscountPercent: 4,
    preferredPaymentMethod: "Virement bancaire",
    totalCustomers: 15,
    totalSites: 22,
    totalUnits: 520,
    totalAnnualRevenue: 2100000,
    lastStatisticsUpdateDate: "2024-08-15T10:00:00Z",
    frameworkContractStartDate: "2023-09-01",
    frameworkContractEndDate: "2024-08-31",
    frameworkContractReference: "CONT-2023-078",
    autoRenewalFrameworkContract: false,
    internalNotes: "Contrat suspendu suite à des retards de paiement importants. Suivi juridique en cours.",
    commercialNotes: "Renégociation en cours avec nouvelles conditions de paiement.",
    contacts: [],
    created: "2023-08-15T15:00:00Z",
    createdBy: "admin@gmao.fr",
    lastModified: "2024-09-01T14:00:00Z",
    lastModifiedBy: "juridique@gmao.fr",
  },
];

// Mock Statistics
export const mockStats: PropertyGroupStats = {
  totalGroups: mockPropertyGroups.length,
  activeGroups: mockPropertyGroups.filter(g => g.status === PropertyGroupStatus.Active).length,
  prospectGroups: mockPropertyGroups.filter(g => g.status === PropertyGroupStatus.Prospect).length,
  totalCustomers: mockPropertyGroups.reduce((sum, g) => sum + g.totalCustomers, 0),
  totalSites: mockPropertyGroups.reduce((sum, g) => sum + g.totalSites, 0),
  totalRevenue: mockPropertyGroups.reduce((sum, g) => sum + g.totalAnnualRevenue, 0),
};

// Helper function to get contacts by property group ID
export const getContactsByPropertyGroupId = (propertyGroupId: string): PropertyGroupContact[] => {
  return mockContacts.filter(contact => contact.propertyGroupId === propertyGroupId);
};

// Helper function to get a single property group by ID
export const getPropertyGroupById = (id: string): PropertyGroup | undefined => {
  const group = mockPropertyGroups.find(g => g.id === id);
  if (group) {
    return {
      ...group,
      contacts: getContactsByPropertyGroupId(id),
    };
  }
  return undefined;
};